### ISSUE TITLE
Question about the function load_sc in enigma toolbox

### ISSUE THREAD

**Issue by WY-SHI** [MICA-MNI/ENIGMA#26]
Hi, thank you for providing the efficient toolbox.
Recently, I checked the Structural Connectivity data return by `load_sc`, but I found the values in the matrix have negative ones with the parcellation ['schaefer_100', 'schaefer_200', 'schaefer_300', 'schaefer_400', 'glasser_360'], except 'aparc'.  Are these negative values normal?

**Comment by saratheriver** [comment]
Hello!

Yes, they are absolutely normal. This is because the group-average normative structural connectomes were defined using a distance-dependent thresholding procedure (https://doi.org/10.1162/netn_a_00075)—which preserves the edge length distribution in individual patients—and were log transformed to reduce connectivity strength variance. 

In the higher resolution parcellations (eg 100+), some parcels had a fraction value, and since we are taking the log, then it becomes a negative value. 

Hope this clears things up,

Sara.
